#!/bin/bash

. faustpath
. usage.sh

# change if you want to get the log of what's happening
LOG="/dev/null"

# exit if a command fails
set -e

# global option variables
LIB="0"
NVOICES=0
MIDI=0

echoHelp()
{
    echo "faust2ananas [-lib] [-midi] [-nvoices <num>] [Faust options (-vec -vs 8...)] <file.dsp>"
    option
    option -lib "generates a package containing an object compatible with the Ananass audio library"
    option -midi
    option "-nvoices <num>"
    option "Faust options"
    exit
}

if [ "$#" -eq 0 ]; then
    echo 'Please, provide a Faust file to process !'
    echo ''
    echoHelp
fi

###########################
# Processing Arguments
###########################

while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echoHelp
    elif [ $p = "-nvoices" ]; then
        shift
        NVOICES=$1
    elif [ $p = "-midi" ]; then
        MIDI=1
    elif [[ -f "$p" ]] && [ ${p: -4} == ".dsp" ]; then
        FILE="$p"
    elif [ $p = "-lib" ]; then
        LIB=1
    else
        OPTIONS="$OPTIONS $p"
    fi

shift

done

###########################
# Post Argument Processing
###########################

BASENAME=$(basename "$FILE")
MODULENAME="${BASENAME%.dsp}"

###########################
# Generating a lib package
###########################

if [ $LIB -eq 1 ]; then
    DIR=../lib/$MODULENAME/src
    mkdir -p $DIR
    rm -f $DIR/$MODULENAME.cpp $DIR/$MODULENAME.h
    faust $OPTIONS -uim -a ananas.cpp -i $FILE -o $DIR/$MODULENAME.cpp
    if [ $NVOICES -gt 0 ]; then
        echo '#define NVOICES '$NVOICES >> $DIR/$MODULENAME.h
    fi
    if [ $MIDI -eq 1 ]; then
        echo '#define MIDICTRL' >> $DIR/$MODULENAME.h
    fi
    cat ananas.h >> $DIR/$MODULENAME.h
    TMP=$(awk -v modName="$MODULENAME" '{gsub(/AudioFaust/,modName)}1' $DIR/$MODULENAME.cpp)
    echo "$TMP" > $DIR/$MODULENAME.cpp
    TMP=$(awk -v modName="$MODULENAME" '{gsub(/AudioFaust/,modName)}1' $DIR/$MODULENAME.h)
    echo "$TMP" > $DIR/$MODULENAME.h
    TMP=$(awk -v modName="$MODULENAME.h" '{gsub(/ananas.h/,modName)}1' $DIR/$MODULENAME.cpp)
    echo "$TMP" > $DIR/$MODULENAME.cpp
    TMP=$(awk -v modName="faust_$MODULENAME" '{gsub(/faust_ananas/,modName)}1' $DIR/$MODULENAME.h)
    echo "$TMP" > $DIR/$MODULENAME.h
fi
